version: "3.0"
services:

  php:
    build: php/
    container_name: php7
    volumes:
      - ~/Desktop/examDocker/sites/:/var/www/html/
    ports:
      - '8080:80'

  mariadb:
    image: mariadb:10.1
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=c9V8mjcpi9q8zv9xpoGx3K3eyiBX4chDnXtnouiKsndQUgBxXg4uYCw4tkTZWNyZ
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: myAdmin
    restart: always
    links:
      - mariadb:db
    ports:
      - '8900:80'